### PR TITLE
DM-6629: API for metric measurements and serialization

### PR DESCRIPTION
**Pull request by jonathansick**
This PR implements a new system of json-serializable objects and base classes that can be used to implement metric measurement codes. The goal is to provide a consistent API for building tools that report metric measurements to SQuaSH.

**Please see documentation at https://validate-drp.lsst.io/v/DM-6917/index.html**. API and user guide documentation is being prototyped in another ticket (DM-6917), but I think that reviewing that content will aid in understanding the API design presented here.
## Progress overview
- [x] Design and implement a new system of serializable base classes
- [x] Refactor `loadAndMatchData`, `analyzeData`, `checkAstrometry` and `checkPhotometry` into new classes
- [ ] YAML-based metric definitions
  - [x] First draft of YAML schema
  - [ ] Write schema formal validator
  - [x] Write factory function to build MetricBase-derived objects from YAML definitions.
- [x] Port metric measurements to new classes
  - [x] PA1
  - [x] PF1
  - [x] PA2
  - [x] AMx
  - [x] AFx
  - [x] ADx
- [x] Re-wire exisiting `validate_drp` functionality
  - [x] Plotting
  - [x] Pass/fail check
  - [x] Summary printout
- [x] Solve inter-dependent metric specification levels issue
- [x] Solve bandpass-dependent specification levels issue
## New base classes

The `base` module includes a set of basic classes and abstract base classes that can be used to build a JSON-serializable measurement task; like `validate_drp`. Indeed, the classes in `base` could easily be used by other codes that measure metrics during integration tests. Briefly, these classes are:
- `JsonSerializationMixin`: all classes that should be serialized into a Job document are derived from this class. This class ensures that subclasses implement a `json` property that renders a JSON-compatible dict. This mixin class also provides helpers for rendering lists and dicts of other objects derived on `JsonSerializationMixin`.
- `Datum`: a class that allows values (either scalars or arrays) to be annotated with units, labels and descriptions.
- `Metric`: a class for Metric definition objects. Metric objects includes basic spec levels (see below), and also include logic for comparing a measurement against a spec level.
- `Specification` contain the scalar level of a metric specification, as well as dependencies of the measurement.
- `MeasurementBase` is derived from `JsonSerializationMixin` and is used to make measurement classes that contains both code and results of a measurement. It also is able to link to `Blob` objects, making introspection possible in the SQuaSH UI.
- `BlobBase` is derived from `JsonSerializationMixin` and can be used to make blob data containers. The idea is that data reduction can occur in a subclass of `BlobBase`. The results of that data reduction are then available as attributes to measurement classes, and the blob itself can be serialized to JSON.
## Changes to the original `validate_drp` implementation
- The `loadAndMatchData` and `analyzeData` functions are now contained in a `MatchedMultiVisitDataset` class (subclass of `BlobBase`) in `matchreduce` module
- `checkAstrometry` is now in the `AnalyticAstrometryModel` class (subclass of `BlobBase`) in `matchreduce` module
- `checkPhotometry` is now in the `AnalyticPhotometryModel` class (subclass of `BlobBase`) in `matchreduce` module
- Functions from the `check` module are now contained in `util`.
- Serialization classes introduced in DM-6086 are now mostly removed from the `io` module (being replaced by the classes in `base`). The `JobSerializer` is currently the only class that remains in `io`.
- The `calcSrd` module is now `calcsrd`, and implemented as a subpackage. Each measurement (for the most part) will have its own submodule. However, each measurement class will be imported in `calcsrd.__init__`, keeping a clean namespace.
### Handling of inter-dependent metric specifications.

For example, `PF1` can be thought of as a configuration input for `PA1`. This needs to be handled explicitly by design to avoid ambiguities in the SQuaSH and in reports.

Related to this is the fact that interdependent metric specifications also imply multiple input parameters for a measurement at each specification level, and therefore multiple measurement values. The existing PA1 implementation gets around this by only reporting a measurement for a 'default' specification level.
#### Solution
1. Specifications can have dependencies, which can either be interpreted as a Datum, or as a Metric. When the dependency is a Metric, a copy of that Metric object is included in the specification, allowing the spec levels of dependencies to be used in measurement codes.
2. Each Measurement has a `specLevel` property that can be set to a specification level name (design, minimum, stretch) to declare that this measurement is specific to that level. This happens when a measurement is dependent on a specification level of another metric. This property will be `None` if the Measurement is not level-specific. Serialized to JSON as `spec_level`.
### Handling of bandpass-dependent specification levels

For example, PA1, PF1, PA2 specification levels are bandpass-dependent:

> The listed values apply to the g, r and i bands. The PA1 and PA2 values in the u, z and y bands may be 50% larger.

Having relaxed specification levels for the 'extreme' bandpasses is quite common across [LPM-17](https://docushare.lsstcorp.org/docushare/dsweb/Get/LPM-17) and needs to be handled coherently in this design.
#### Solution

This problem is solved in the following ways
- Specifications are annotated with the bandpasses that they refer to (or `None` if the spec is bandpass agnostic).
- Metrics have a `getSpec` method that attempts to resolve the appropriate specification based on both the level's name (e.g., design, minimum, stretch) _and_ any bandpasses if they are supplied.
- MeasurementBase classes can also track bandpass and pass that information to `getSpec` when doing a `checkSpec`.
### Handling of measurements that generate more than a scalar

For example, AMx generates an array of RMS distances. These are used by other measurements.
#### Solution

Measurements can generate blobs containing these values. Other Measurement classes can use data in these blobs (and link to those blobs in their json).
### YAML-driven metric specification

Instead of hard-coding metric definitions into classes, should they be defined in a YAML file that is then used to create the Metric classes?
#### Solution

See `metrics.yaml` for a draft of such a metric specification file. More words to follow on the schema.

### CODE REVIEW

**Comment by jonathansick** [comment]
Sample print output from running `validateDrp.py` (failures are colorized in the terminal)

```
=================================================================
r band metric measurements                                       
=================================================================
PA1 - LPM-17, p. 21, http://ls.st/lpm-17                         
The maximum rms of the unresolved source magnitude               
distribution around the mean value (repeatability).              
        Failed stretch      16.0336 <= 3.0000 mmag               
        Failed minimum      16.0336 <= 8.0000 mmag               
        Failed design       16.0336 <= 5.0000 mmag               
PF1 - LPM-17, p. 21, http://ls.st/lpm-17                         
The maximum fraction of magnitudes deviating by more than PA2    
from mean (%).                                                   
        Failed stretch      23.4432 <= 5.0000                    
        Passed minimum      17.5824 <= 20.0000                   
        Failed design       17.5824 <= 10.0000                   
PA2 - LPM-17, p. 21, http://ls.st/lpm-17                         
At most PF1 % of magnitudes may deviate by more than this        
from the mean (millimag).                                        
        Failed stretch      42.9974 <= 10.0000 mmag              
        Failed minimum      25.1150 <= 15.0000 mmag              
        Failed design       32.9696 <= 15.0000 mmag              
AM1 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum rms of the astrometric distance distribution for     
stellar pairs with separations of D=5 arcmin (repeatability)     
(milliarcsec).                                                   
        Failed stretch      7.8074 <= 5.0000 mmag                
        Passed minimum      7.8074 <= 20.0000 mmag               
        Passed design       7.8074 <= 10.0000 mmag               
AM2 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum rms of the astrometric distance distribution for     
stellar pairs with separations of D=20 arcmin (repeatability)    
(milliarcsec).                                                   
        Failed stretch      7.1721 <= 5.0000 mmag                
        Passed minimum      7.1721 <= 20.0000 mmag               
        Passed design       7.1721 <= 10.0000 mmag               
AM3 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum rms of the astrometric distance distribution for     
stellar pairs with separations of D=200. arcmin (repeatability)  
(milliarcsec).                                                   
        Skipped stretch      no measurement                      
        Skipped minimum      no measurement                      
        Skipped design       no measurement                      
AF1 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum fraction of astrometric distances which deviate      
by more than ADx milliarcsec (see AMx) (%)                       
        Failed stretch      21.0326 <= 5.0000                    
        Passed minimum      1.6504 <= 20.0000                    
        Passed design       9.2679 <= 10.0000                    
AF2 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum fraction of astrometric distances which deviate      
by more than ADx milliarcsec (see AMx) (%)                       
        Failed stretch      14.0704 <= 5.0000                    
        Passed minimum      0.7538 <= 20.0000                    
        Passed design       4.8367 <= 10.0000                    
AF3 - LPM-17, p. 23, http://ls.st/lpm-17                         
The maximum fraction of astrometric distances which deviate      
by more than ADx milliarcsec (see AMx) (%)                       
        Skipped stretch      no measurement                      
        Skipped minimum      no measurement                      
        Skipped design       no measurement                      
AD1 - LPM-17, p. 23, http://ls.st/lpm-17                         
No more than AFx of the astrometric distances will deviate by    
more than this from the median (see AMx, AFx) (milliarcsec).     
        Failed stretch      35.2222 <= 10.0000 milliarcsecond    
        Passed minimum      17.5310 <= 40.0000 milliarcsecond    
        Failed design       25.8893 <= 20.0000 milliarcsecond    
AD2 - LPM-17, p. 23, http://ls.st/lpm-17                         
No more than AFx of the astrometric distances will deviate by    
more than this from the median (see AMx, AFx) (milliarcsec).     
        Failed stretch      25.9902 <= 10.0000 milliarcsecond    
        Passed minimum      13.2266 <= 40.0000 milliarcsecond    
        Passed design       18.9263 <= 20.0000 milliarcsecond    
AD3 - LPM-17, p. 23, http://ls.st/lpm-17                         
No more than AFx of the astrometric distances will deviate by    
more than this from the median (see AMx, AFx) (milliarcsec).     
        Skipped stretch      no measurement                      
        Skipped minimum      no measurement                      
        Skipped design       no measurement                      

=================================================================
r band summary                                                   
=================================================================
Failed design       12 of 21 failed                              
Failed minimum      6 of 21 failed                               
Failed stretch      18 of 21 failed
```

**Comment by jonathansick** [comment]
## Sample photometry model plot

cfht_output_r_check_photometry

## Sample astrometry model plot

cfht_output_r_check_astrometry

## Sample PA1 plot

cfht_output_r_pa1

## Sample AM1 plot

cfht_output_r_am1_d_5_arcmin_17 0_21 5

## Sample AM2 plot

cfht_output_r_am2_d_20_arcmin_17 0_21 5

**Comment by jonathansick** [comment]
Just heard on HipChat that underscore (PEP8) names for Python variables/functions/methods _is_ actually allowed. I'd like to update this ticket to use the new naming throughout so that we're future proof.

**Comment by ktlim** [comment]
PEP8 is allowed (not by the letter of the law at this point but by special dispensation :) ) _if you do it for the entire package_.

**Comment by jonathansick** [comment]
Closing this ticket. Design review will continue on #21.

**Pull request closed without merging**
