### PR TITLE
Small improvements I noticed

### PR DESCRIPTION
**Pull request by PaulPrice**

### CODE REVIEW

**Comment by wmwv** [comment]
Thanks for the suggestions.  Could you wrap these in a DM-\* ticket and put the branch to merge there?

**Comment by wmwv** [comment]
Oh, I should have looked first to see how trivial these are.  I see why you just submitted these request directly.
1. I'm hesitant to require a particular backend.  Is there a way to say: "whatever reasonable backend you have available that's not X11?"  <Insert matplotlib rant here.>
2. Thanks for the note about footprints.  That sounds good and useful.  I've started a new ticket about making `validate_drp` faster.  https://jira.lsstcorp.org/browse/DM-5819

**Comment by PaulPrice** [comment]
Regarding matplotlib, explicitly selecting the `Agg` backend is a common solution to the problem (e.g., http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined) and it's what we've used for HSC (https://github.com/HyperSuprime-Cam/hscPipe/blob/master/python/hsc/pipe/tasks/plotSetup.py).  It seems to be generally available, so I'm not afraid that people don't have it.

This should not be something the user needs to select (e.g., via matplotlib config files), because it's _the code_ that doesn't use X11 and the user doesn't know that.  Besides, the user may want a different default backend for some other code and so it's not right to force him to modify his default for one piece of code.

**Comment by wmwv** [comment]
I'm a bit sensitive about this because 'Agg' was broken on my platform for a while.  (Yes, this is clearly a Very Bad Thing.)

**Comment by timj** [comment]
So how do you let matplotlib use the `.matplotlibrc` file in preference to that hard-coded in the source file? Seems like you'd want a scheme whereby you can specify a fallback in the source file not an override. Is that possible?

**Comment by wmwv** [comment]
I would love to know the answer to that.

Do we have a Displaying Things in Python Working Group?

**Comment by jonathansick** [comment]
_Do we ever want validate_drp to use a backend other than Agg?_ Agg is available with every Matplotlib installation. Agg is the de-facto backend for making plots that are saved to files (PDF, PNG). We should just use it.

As I stated in #13, `validate_drp` is a bad experience for anyone using a machine where they haven't configured Matplotlib and don't have a display (i.e., a generic cloud VM). Either we need to have Eups install a `.matplotlibrc` in the user's working directory or (much better) let's all just specify Agg explicitly as @PaulPrice suggests here (or in the object-oriented Matplotlib model as I suggested in #13). As it stands, `validate_drp` will probably fail if implemented in an automated QA workflow.

**Comment by RobertLuptonTheGood** [comment]
As I said somewhere or other, I don't want user code to know anything about matplotlib backends.  I understand why the solution "put something sane in your ~/.matplotlibrc file" is unacceptable, but asking users to explicitly request Agg is too, unless wrapped in a utility function that can be called as a black box.  I don't want more matplotlib knowledge than absolutely necessary put into our code, but that's a topic that I'll raise on c.l.o.

**Pull request closed without merging**
